#!/usr/bin/env bash

sleep 1
clear

DOTFILES="$HOME/.yame"

echo -e "\e[90m:: Updating system & install \e[1;3;94mgum\e[0m"
echo
sudo pacman -Syu --needed git gum

if [ ! -d "$DOTFILES/" ]; then
  mkdir -p "$DOTFILES/" &>/dev/null
  echo -e "\e[90m:: Cloning dotfiles to \e[1;3;94m$DOTFILES\e[0m"
  echo
  FORMAT=$(gum choose "HTTPS" "SSH" "Abort")

  if [ "$FORMAT" == "HTTPS" ]; then
    git clone "https://github.com/YetAnotherMechanicusEnjoyer/dotfiles.git" "$DOTFILES/"
  elif [ "$FORMAT" == "SSH" ]; then
    git clone "git@github.com:YetAnotherMechanicusEnjoyer/dotfiles.git" "$DOTFILES/"
  elif [ "$FORMAT" == "Abort" ]; then
    echo -e "\e[0;90m:: Setup aborted.\e[0m"
    exit 0
  fi
else
  echo -e "\e[90m:: \e[1;93mWARN\e[0;90m - \e[1;3;94m$DOTFILES/\e[0;90m already exists\e[0m"
  echo -e "\e[0;90m:: Press \e[1;94m[ENTER]\e[0;90m to close.\e[0m"
  read
fi

echo -e "\n\e[1m\e[94mDo you want to configure pacman ?\e[0m"
gum confirm && sh "$DOTFILES/scripts/setup/pacman.sh"

clear
echo -e "\n\e[1m\e[94mDo you want to install packages ?\e[0m"
gum confirm && sh "$DOTFILES/scripts/setup/packages.sh"

clear
echo -e "\n\e[1m\e[94mDo you want to install yay ?\e[0m"
gum confirm && sh "$DOTFILES/scripts/setup/yay.sh"

clear
echo -e "\n\e[1m\e[94mDo you want to configure git ?\e[0m"
gum confirm && sh "$DOTFILES/scripts/setup/git.sh"

clear
echo -e "\n\e[1m\e[94mDo you want to configure tmux ?\e[0m"
gum confirm && sh "$DOTFILES/scripts/setup/tmux.sh"

clear
echo -e "\n\e[1m\e[94mDo you want to clone some repos ?\e[0m"
gum confirm && sh "$DOTFILES/scripts/setup/repo.sh"

clear
echo -e "\n\e[1m\e[94mDo you want to install Lxtharia's minegrub theme ?\e[0m"
gum confirm && sh "$DOTFILES/scripts/setup/grub.sh"

clear
echo -e "\n\e[1m\e[94mDo you want to install Davi-S's minesddm ?\e[0m"
gum confirm && sh "$DOTFILES/scripts/setup/sddm.sh"

clear
echo -e "\n\e[1m\e[94mDo you want to install other dotfiles ?\e[0m"
action=$(gum choose "ML4W" "end-4" "no")

clear
if [[ $action == "ML4W" ]]; then
  sh "$DOTFILES/scripts/setup/ml4w_install.sh"
elif [[ $action == "end-4" ]]; then
  bash <(curl -sSf https://ii.clsty.link/get)
fi

clear
echo -e "\n\e[1m\e[94mDo you want to link config files ?\e[0m"
gum confirm && sh "$DOTFILES/scripts/setup/link.sh"

clear
