#!/usr/bin/env bash

sleep 1
clear

export DOTFILES="$HOME/.yame"
export REPODIR="$HOME/.yamerepo"

printf "\e[0;1;93m"
if command -v "figlet" >/dev/null; then
  figlet -f smslant "Setup"
else
  echo "   ____    __ "
  echo "  / __/__ / /___ _____ "
  echo " _\ \/ -_) __/ // / _ \ "
  echo "/___/\__/\__/\_,_/ .__/ "
  echo "                /_/ "
fi
echo -e "\e[0m"

echo -e "\e[0;90m:: Setup \e[0;1;3;93mstarted\e[0;90m...\e[0m"
echo -e "\e[0;90m:: Updating \e[1;3;94mpacman\e[0;90m packages & installing \e[1;3;94mgum & git\e[0m"
echo
sudo pacman -Syu --needed git gum

if [ ! -d "$DOTFILES/" ]; then
  mkdir -p "$DOTFILES/" &>/dev/null
  echo -e "\e[0;90m:: Cloning dotfiles to \e[1;3;94m$DOTFILES\e[0m"
  echo
  FORMAT=$(gum choose "HTTPS" "SSH" "Abort")

  if [ "$FORMAT" == "HTTPS" ]; then
    git clone "https://github.com/YetAnotherMechanicusEnjoyer/dotfiles.git" "$DOTFILES/"
  elif [ "$FORMAT" == "SSH" ]; then
    git clone "git@github.com:YetAnotherMechanicusEnjoyer/dotfiles.git" "$DOTFILES/"
  elif [ "$FORMAT" == "Abort" ]; then
    echo -e "\e[0;90m:: Setup aborted.\e[0m"
    exit 0
  fi
  printf "\e[0;90m:: Press \e[1;94m[ENTER]\e[0;90m to continue.\e[0m"
  read
else
  echo
  echo -e "\e[0;90m:: \e[1;93mWARN\e[0;90m - \e[1;3;94m$DOTFILES/\e[0;90m already exists\e[0m"
  printf "\e[0;90m:: Press \e[1;94m[ENTER]\e[0;90m to close.\e[0m"
  read
fi

clear
gum confirm "Do you want to configure pacman ?" && sh "$DOTFILES/scripts/setup/pacman.sh"

clear
gum confirm "Do you want to install yay ?" && sh "$DOTFILES/scripts/setup/yay.sh"

clear
gum confirm "Do you want to install packages ?" && sh "$DOTFILES/scripts/setup/packages.sh"

clear
gum confirm "Do you want to configure git ?" && sh "$DOTFILES/scripts/setup/git.sh"

clear
gum confirm "Do you want to configure tmux ?" && sh "$DOTFILES/scripts/setup/tmux.sh"

clear
gum confirm "Do you want to clone some repos ?" && sh "$DOTFILES/scripts/setup/repo.sh"

clear
gum confirm "Do you want to install Lxtharia's minegrub theme ?" && sh "$DOTFILES/scripts/setup/grub.sh"

clear
gum confirm "Do you want to install Davi-S's minesddm ?" && sh "$DOTFILES/scripts/setup/sddm.sh"

clear
echo -e " \e[0;1;34mDo you want to install other dotfiles ?\e[0m\n"
action=$(gum choose "ML4W" "end-4" "no")

clear
if [[ $action == "ML4W" ]]; then
  bash <(curl -sSf https://ml4w.com/os/stable)
elif [[ $action == "end-4" ]]; then
  bash <(curl -sSf https://ii.clsty.link/get)
fi

clear
gum confirm "Do you want to link config files ?" && sh "$DOTFILES/scripts/setup/link.sh"

clear
gum confirm "Do you want to reboot your system ?" && reboot

echo -e "\e[0;90m:: Setup \e[1;3;92mcompleted\e[0;90m!\e[0m"
printf "\e[0;90m:: Press \e[1;94m[ENTER]\e[0;90m to close.\e[0m"
read
