export DOTFILES_PATH="$HOME/.yame"
export DEBUGINFOD_URLS="https://debuginfod.archlinux.org"
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PATH:$HOME/.tmuxifier/bin:$HOME/scripts:$HOME/.cargo/bin:$HOME/scripts:$PNPM_HOME"
export EDITOR="nvim"
