# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

windowrule {
    name = fix-starcitizen
    match:class = starcitizen
    opaque = true
}

windowrule {
  name = sameboy-float
  match:class = sameboy
  float = on
  size = 800 720
}

windowrule {
  name = "miniquad-float"
  match:class = miniquad-application
  float = on
  center = true
}

windowrule {
  name = "sepsis"
  match:class = sepsis
  float = on
  center = true
}

windowrule = match:class memeblink, match:title MemeBlink Overlay, float on
windowrule = match:class memeblink, match:title MemeBlink Overlay, pin on
windowrule = match:class memeblink, match:title MemeBlink Overlay, no_focus on
windowrule = match:class memeblink, match:title MemeBlink Overlay, no_shadow on
windowrule = match:class memeblink, match:title MemeBlink Overlay, no_anim on
windowrule = match:class memeblink, match:title MemeBlink Overlay, no_blur on
windowrule = match:class memeblink, match:title MemeBlink Overlay, border_size 0
windowrule = match:class memeblink, match:title MemeBlink Overlay, no_dim on
windowrule = match:class memeblink, match:title MemeBlink Overlay, opacity override 0.999 override

#
#windowrule {
#  name = "memeblink dashboard"
#  match:title = MemeBlink - Dashboard
#  float = true
#  center = true
#}
