#!/usr/bin/env bash
#    ____         __       ____               __     __
#   /  _/__  ___ / /____ _/ / / __ _____  ___/ /__ _/ /____ ___
#  _/ // _ \(_-</ __/ _ `/ / / / // / _ \/ _  / _ `/ __/ -_|_-<
# /___/_//_/___/\__/\_,_/_/_/  \_,_/ .__/\_,_/\_,_/\__/\__/___/
#                                 /_/
#
# I (YetAnotherMechanicusEnjoyer) took inspiration from Stephan Rabbe's ML4W

_checkCommandExists() {
  cmd="$1"
  if ! command -v "$cmd" >/dev/null; then
    return 1
  fi
  return 0
}

_pull() {
  local dir="$1"
  local pre_pull_sha
  local post_pull_sha

  pre_pull_sha=$(git -C "$dir" rev-parse HEAD)
  git -C "$dir" pull >&/dev/null
  post_pull_sha=$(git -C "$dir" rev-parse HEAD)

  if [[ "$pre_pull_sha" != "$post_pull_sha" ]]; then
    git -C "$dir" log --oneline --graph --color "${pre_pull_sha}".."${post_pull_sha}" | sed 's/^/   /'
    echo
    return 0
  else
    echo -e "   \e[0;90mAlready up to date.\e[0m\n"
    return 1
  fi
}

_buildZig() {
  echo -e "\e[0;1;90m   \e[0;1;3;93mzig\e[0;90m build --build-file \e[0;3;94m$1/build.zig\e[0;90m -j\"\$(nproc)\"\e[0m"
  zig build --build-file "$1/build.zig" -j"$(nproc)" -Doptimize=ReleaseFast
}

_buildCargo() {
  echo -e "\e[0;1;90m   \e[0;1;3;91mcargo\e[0;90m build --m \e[0;3;94m$1/Cargo.toml\e[0;90m -j \"\$(nproc)\" --release\e[0m"
  cargo build -m "$1/Cargo.toml" -j "$(nproc)" --release
}

_buildMakefile() {
  echo -e "\e[0;1;90m   \e[0;1;3;97mmake\e[0;90m -C \e[0;3;94m$1\e[0;90m -j \"\$(nproc)\"\e[0m"
  make -C "$1" -j "$(nproc)"
}

_buildCMake() {
  echo -e "\e[0;1;90m   \e[0;1;3;96mcmake\e[0;90m -S \e[0;3;94m$1\e[0;90m -B $2 && cmake --build $2 --parallel \"\$(nproc)\"\e[0m"
  cmake -S "$1" -B "$2" && cmake --build "$2" --parallel "$(nproc)"
}

_compile() {
  local dir="$1"
  echo -e "\e[0;90m   Compiling \e[0;1;3;94m$entry\e[0;90m...\e[0m"

  [[ -f "$dir/build.zig" ]] && _buildZig "$dir"
  [[ -f "$dir/Cargo.toml" ]] && _buildCargo "$dir"
  [[ -f "$dir/Makefile" ]] && _buildMakefile "$dir"
  [[ -f "$dir/CMakeLists.txt" ]] && _buildCMake "$dir" "$dir/build"
}

sleep 1
clear
printf "\e[0;1;93m"
if _checkCommandExists "figlet"; then
  figlet -f smslant "Updates"
else
  echo "Updates"
fi
printf "\e[0m"

echo
if gum confirm "Do you want to start the update now?"; then
  echo
  echo -e "\e[0;1;90m:: Update \e[0;1;3;93mstarted\e[0;1;90m...\e[0m"
elif [ $? -eq 130 ]; then
  exit 130
else
  echo
  echo -e "\e[0;1;90m:: Update \e[0;1;3;91mcanceled\e[0;1;90m.\e[0m"
  exit
fi

# Pacman
if _checkCommandExists "pacman"; then
  if _checkCommandExists "yay"; then
    yay
  elif _checkCommandExists "paru"; then
    paru -Syu --noconfirm
  else
    pacman -Syu --noconfirm
  fi
else
  echo -e "\e[0;1;90m:: \e[0;1;91mERROR\e[0;1;90m - Script is made for \e[0;1;3;96mArch Linux\e[0;1;90m only\e[0m"
  printf "\e[0;90m:: Press \e[1;94m[ENTER]\e[0;90m to close.\e[0m"
  read
  exit 1
fi
echo

# Flatpak
if _checkCommandExists "flatpak"; then
  echo -e "\e[0;1;90m:: Searching for \e[0;1;3;94mFlatpak\e[0;90m updates...\e[0m"
  flatpak update
  echo
fi

# Rustup
if _checkCommandExists "rustup"; then
  echo -e "\e[0;1;90m:: Updating \e[0;1;3;94mrustup\e[0m"
  rustup update
  echo
fi

# Zinit
if _checkCommandExists "zsh"; then
  SKIP_EXEC_ZSH=1 zsh -i -c '
    if type zinit >/dev/null 2>&1; then
      echo -e "\e[0;1;90m:: Updating \e[0;1;3;94mzinit\e[0m"
      zinit self-update
      zinit update
      echo
    fi
  '
fi

# pnpm
if _checkCommandExists "pnpm"; then
  echo -e "\e[0;1;90m:: Updating \e[0;1;3;94mpnpm\e[0m"
  pnpm self-update
  echo
fi

# dotfiles
dotfiles_repo="YetAnotherMechanicusEnjoyer/dotfiles"
if [[ -d "$DOTFILES/.git" ]]; then
  echo -e "\e[0;1;90m:: Updating \e[0;1;3;94m$dotfiles_repo\e[0m"
  _pull "$DOTFILES"
fi

# dotfiles repositories
if [[ -d "$REPODIR" ]]; then
  for entry in "$REPODIR"/*; do
    [[ ! -d "$entry/.git" ]] && continue

    url=$(git -C "$entry" remote get-url origin 2>/dev/null)
    author=$(echo "$url" | sed -E 's/\.git$//; s/.*[:\/]([^\/]+)\/[^\/]+$/\1/')
    [[ -z "$author" ]] && author="local"

    repo="${entry##*/}"

    echo -e "\e[0;1;90m:: Updating \e[0;1;3;94m$author/$repo\e[0m"

    if _pull "$REPODIR/$repo"; then
      if [[ "$repo" != *"template"* ]]; then
        _compile "$REPODIR/$repo"
      else
        echo -e "   \e[0;90mNo need to compile template repositories\e[0m"
      fi
    fi
    echo
  done
fi

# Reload Waybar
pkill -RTMIN+1 waybar

echo -e "\e[0;1;90m:: Update \e[0;1;3;92mcomplete\e[0;90m!\e[0m"
printf "\e[0;90m:: Press \e[1;94m[ENTER]\e[0;90m to close.\e[0m"
read
