#!/usr/bin/env bash
#    ____         __       ____               __     __
#   /  _/__  ___ / /____ _/ / / __ _____  ___/ /__ _/ /____ ___
#  _/ // _ \(_-</ __/ _ `/ / / / // / _ \/ _  / _ `/ __/ -_|_-<
# /___/_//_/___/\__/\_,_/_/_/  \_,_/ .__/\_,_/\_,_/\__/\__/___/
#                                 /_/
#
# I (YetAnotherMechanicusEnjoyer) took inspiration from Stephan Rabbe's ML4W

_checkCommandExists() {
  cmd="$1"
  if ! command -v "$cmd" >/dev/null; then
    return 1
  fi
  return 0
}

sleep 1
clear
printf "\e[0;1;93m"
if _checkCommandExists "figlet"; then
  figlet -f smslant "Updates"
else
  echo "Updates"
fi
printf "\e[0m"

echo
if gum confirm "Do you want to start the update now?"; then
  echo
  echo -e "\e[0;1;90m:: Update \e[0;1;3;93mstarted\e[0;1;90m...\e[0m"
elif [ $? -eq 130 ]; then
  exit 130
else
  echo
  echo -e "\e[0;1;90m:: Update \e[0;1;3;91mcanceled\e[0;1;90m.\e[0m"
  exit
fi

# Pacman
if _checkCommandExists "pacman"; then
  if _checkCommandExists "yay"; then
    yay
  elif _checkCommandExists "paru"; then
    paru -Syu --noconfirm
  else
    pacman -Syu --noconfirm
  fi
else
  echo -e "\e[0;1;90m:: \e[0;1;91mERROR\e[0;1;90m - Script is made for \e[0;1;3;96mArch Linux\e[0;1;90m only\e[0m"
  printf "\e[0;90m:: Press \e[1;94m[ENTER]\e[0;90m to close.\e[0m"
  read
  exit 1
fi
echo

# Flatpak
if _checkCommandExists "flatpak"; then
  echo -e "\e[0;1;90m:: Searching for \e[0;1;3;94mFlatpak\e[0;90m updates...\e[0m"
  flatpak update
  echo
fi

# Rustup
if _checkCommandExists "rustup"; then
  echo -e "\e[0;1;90m:: Updating \e[0;1;3;94mrustup\e[0m"
  rustup update
  echo
fi

# Zinit
if _checkCommandExists "zsh"; then
  SKIP_EXEC_ZSH=1 zsh -i -c '
    if type zinit >/dev/null 2>&1; then
      echo -e "\e[0;1;90m:: Updating \e[0;1;3;94mzinit\e[0m"
      zinit self-update
      zinit update
      echo
    fi
  '
fi

# Reload Waybar
pkill -RTMIN+1 waybar

echo -e "\e[0;1;90m:: Update \e[0;1;3;92mcomplete\e[0;90m!\e[0m"
printf "\e[0;90m:: Press \e[1;94m[ENTER]\e[0;90m to close.\e[0m"
read
